networks: (( merge ))

meta:
  environment: ~
  job_templates: (( merge ))

jobs:
- name: aerospike_server
  instances: 1
  templates:
  - name: aerospike_server
    release: aerospike-managed-service
  resource_pool: aerospike-nodes
  networks:
  - name: aerospike-nodes

- name: aerospike_service_broker
  instances: 1
  templates: 
  - name: aerospike_service_broker
    release: aerospike-managed-service
  resource_pool: vms
  networks:
  - name: default


